### ISSUE TITLE
It wont work for me.

### ISSUE THREAD

**Issue by ghost** [akirarat/cr-patcher#10]
C:\Users\no\Desktop\cr-patcher-master>"C:\Users\Omrtha\AppData\Local\Programs\Python\Python36-32\python.exe" patcher.py  --json 1.9.2
Getting config ...
Checking environment ...
client.keystore does not exist. Would you like to create it? (y/n): y
Traceback (most recent call last):
  File "patcher.py", line 137, in <module>
    result = subprocess.run([config['paths']['keytool'], '-genkey', '-keystore', KEYSTORE_PATH, '-storepass', config['keystore']['storepass'], '-alias', config['keystore']['key']['alias'], '-keypass', config['keystore']['key']['keypass'], '-dname', dname, '-keyalg', 'RSA', '-keysize', '2048', '-validity', '10000'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\no\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\no\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\no\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Help me out,
thanks

**Comment by iluz0r** [comment]
Check the paths in config.json. Mine are:
    "apktool": "C:\\Windows\\apktool.bat",
    "dd": "C:\\Windows\\ddrelease64.exe",
    "keytool": "C:\\Program Files (x86)\\Java\\jdk1.8.0_112\\bin\\keytool.exe",
    "jarsigner": "C:\\Program Files (x86)\\Java\\jdk1.8.0_112\\bin\\jarsigner.exe",
    "zipalign": "C:\\Program Files (x86)\\Android\\android-sdk\\build-tools\\23.0.3\\zipalign.exe"

all with double \
