### ISSUE TITLE
Building APK fails

### ISSUE THREAD

**Issue by erichegit** [akirarat/cr-patcher#4]
What might the problem be if rebuilding of the .apk fails ??

> Patching keys ...
> Patching URLs ...
> Verifying keys ...
> Verifying URLs ...
> Backing up original APK ...
> Rewriting android manifest /home/pi/python_games/cor_proxy/cr-patcher/com.supercell.clashroyale-1.8.1/AndroidManifest.xml
> Building APK ...
> ERROR: Failed to build com.supercell.clashroyale-1.8.1 (W: /tmp/brut_util_Jar_1820504874564873883.tmp: 1: /tmp/brut_util_Jar_1820504874564873883.tmp: Syntax error: word unexpected (expecting ")")

and my 2nd question.
Why at all is patching the APK neccessary?
If I modify the Hosts and redirect game.clashroyale to my proxy IP - isn`t this enougth?
So is patching only to change the URL - or is it manditory to get the proxy working?

**Comment by erichegit** [comment]
Now I was setting up the stuff from scratch on a Debian 8.

No chance to get the patcher run :(
Please can you tell me on which OS you had success with this solution,...

> ...
> Verifying URLs ...
> Backing up original APK ...
> Rewriting android manifest /home/xxx/Downloads/cr-patcher/com.supercell.clashroyale-1.8.1/AndroidManifest.xml
> Building APK ...
> Signing APK ...
> /usr/bin/jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore /home/xxx/Downloads/cr-patcher/client.keystore -storepass teststorepass -keypass testkeypass /home/xxx/Downloads/cr-patcher/com.supercell.clashroyale-1.8.1/build/com.supercell.clashroyale-1.8.1-unsigned.apk testalias
> Aligning APK ...
> Traceback (most recent call last):
>   File "patcher.py", line 515, in <module>
>     result = subprocess.run([config['paths']['zipalign'], '4', UNALIGNED_PATH, PATCHED_PATH], stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
>   File "/usr/local/lib/python3.5/subprocess.py", line 696, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
>     restore_signals, start_new_session)
>   File "/usr/local/lib/python3.5/subprocess.py", line 1540, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> OSError: [Errno 8] Exec format error

**Comment by erichegit** [comment]
can be closed.
Its damn complicated to get all the dependencies running,...
zipalign was not working on my Debian 8 32bit from the "command line tools",...

But a happy end ;)

Just still don`t know why patching is neccessary,...
Isn`t it possible to implement the decryption into the proxy, even if the apk is not patched?

**Comment by aperpen** [comment]
@erichegit Patching is necessary to make the apk connecting to supercell's servers through the proxy

**Comment by ghost** [comment]
Because nobody knows Supercell's private key ;)
